site_name: FastAPI State
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

watch:
  - src
  - README.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path: !relative $config_dir
